# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dfbd492eeb8f902711fcc4e4db1cdaef68d10255ab413c03a3d546e43002b88d4b6e72d72820b136ae001a9503ffbac0cd2827926c30dd1fb8672006a9c0115

test:
  secret_key_base: 24ed20b528d6e94649b74aa3ea4a72abded17b6d84e4391620750665f3689f5b5ec76ec2b75ba4de7ee12026ab144de4fa2d6fb5b0f4c454471471e32242296f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
